# Repository settings set via https://github.com/probot/settings

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: test

  # A short description of the repository that will show up on GitHub
  description: Dummy repo

  # A comma-separated list of topics to set on the repository
  topics: test, testing, dummy

  # A URL with more information about the repository
  homepage: https://test.guillermo.in/

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false
  
  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

labels:
  - name: help wanted
    oldname: help-wanted
    color: 0e8a16
  - name: more-information-needed
    color: d93f0b
  - name: bug
    color: b60205
  - name: feature
    color: 1d76db
  - name: good first issue
    color: "5319e7"
  - name: good second issue
    color: "5319e7"
  - name: good third issue
    color: "5319e7"
  - name: good fourth issue
    color: "5319e7"
  - name: good fifth issue
    color: "5319e7"
