# Repository settings set via https://github.com/probot/settings

repository:
  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: false

topics:
  - test
  - testing
  - dummy

labels:
  - name: help wanted
    oldname: help-wanted
    color: 0e8a16
  - name: more-information-needed
    color: d93f0b
  - name: bug
    color: b60205
  - name: feature
    color: 1d76db
  - name: good first issue
    color: "5319e7"
  - name: good second issue
    color: "5319e7"
  - name: good third issue
    color: "5319e7"
  - name: good fourth issue
    color: "5319e7"
  - name: good fifth issue
    color: "5319e7"
